<?php
defined('ABSPATH') or die();
$language_names = array(
    esc_html__("Disabled", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Afrikaans (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Albanian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Arabic (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Amharic (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Armenian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Belarusian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Bulgarian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Catalan (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Chinese Simplified (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Croatian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Czech (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Danish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Dutch (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("English (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Estonian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Filipino (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Finnish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("French (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Galician (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("German (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Greek (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Hebrew (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Hindi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Hungarian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Icelandic (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Indonesian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Irish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Italian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Japanese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Korean (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Latvian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Lithuanian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Norwegian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Macedonian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Malay (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Maltese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Persian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Polish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Portuguese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Romanian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Russian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Serbian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Slovak (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Slovenian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Spanish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Swahili (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Swedish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Thai (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Turkish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Ukrainian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Vietnamese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Welsh (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Yiddish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Tamil (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Azerbaijani (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Kannada (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Basque (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Bengali (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Latin (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Chinese Traditional (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Esperanto (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Georgian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Telugu (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Gujarati (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Haitian Creole (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Urdu (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Burmese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Bosnian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Cebuano (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Chichewa (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Corsican (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Frisian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Scottish Gaelic (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Hausa (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Hawaian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Hmong (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Igbo (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Javanese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Kazakh (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Khmer (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Kurdish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Kyrgyz (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Lao (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Luxembourgish (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Malagasy (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Malayalam (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Maori (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Marathi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Mongolian (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Nepali (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Pashto (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Punjabi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Samoan (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Sesotho (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Shona (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Sindhi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Sinhala (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Somali (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Sundanese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Swahili (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Tajik (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Uzbek (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Xhosa (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Yoruba (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Zulu (Google Translate)", 'aiomatic-automatic-ai-content-writer'),

    esc_html__("Assammese (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Aymara (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Bambara (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Bhojpuri (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Dhivehi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Dogri (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Ewe (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Guarani (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Ilocano (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Kinyarwanda (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Konkani (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Krio (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Kurdish - Sorani (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Lingala (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Luganda (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Maithili (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Meiteilon (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Mizo (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Odia (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Oromo (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Quechua (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Sanskrit (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Sepedi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Tatar (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Tigrinya (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Tsonga (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Turkmen (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Twi (Google Translate)", 'aiomatic-automatic-ai-content-writer'),
    esc_html__("Uyghur (Google Translate)", 'aiomatic-automatic-ai-content-writer')
);
$language_codes = array(
    "disabled",
    "af",
    "sq",
    "ar",
    "am",
    "hy",
    "be",
    "bg",
    "ca",
    "zh-CN",
    "hr",
    "cs",
    "da",
    "nl",
    "en",
    "et",
    "tl",
    "fi",
    "fr",
    "gl",
    "de",
    "el",
    "iw",
    "hi",
    "hu",
    "is",
    "id",
    "ga",
    "it",
    "ja",
    "ko",
    "lv",
    "lt",
    "no",
    "mk",
    "ms",
    "mt",
    "fa",
    "pl",
    "pt",
    "ro",
    "ru",
    "sr",
    "sk",
    "sl",
    "es",
    "sw",
    "sv",   
    "th",
    "tr",
    "uk",
    "vi",
    "cy",
    "yi",
    "ta",
    "az",
    "kn",
    "eu",
    "bn",
    "la",
    "zh-TW",
    "eo",
    "ka",
    "te",
    "gu",
    "ht",
    "ur",
    "my",
    "bs",
    "ceb",
    "ny",
    "co",
    "fy",
    "gd",
    "ha",
    "haw",
    "hmn",
    "ig",
    "jw",
    "kk",
    "km",
    "ku",
    "ky",
    "lo",
    "lb",
    "mg",
    "ml",
    "mi",
    "mr",
    "mn",
    "ne",
    "ps",
    "pa",
    "sm",
    "st",
    "sn",
    "sd",
    "si",
    "so",
    "su",
    "sw",
    "tg",
    "uz",
    "xh",
    "yo",
    "zu",

    "as",
    "ay",
    "bm",
    "bho",
    "dv",
    "doi",
    "ee",
    "gn",
    "ilo",
    "rw",
    "gom",
    "kri",
    "ckb",
    "ln",
    "lg",
    "mai",
    "mni-Mtei",
    "lus",
    "or",
    "om",
    "qu",
    "sa",
    "nso",
    "tt",
    "ti",
    "ts",
    "tk",
    "ak",
    "ug"
);
$language_names_deepl = array(
  "English (DeepL)",
  "German (DeepL)",
  "French (DeepL)",
  "Spanish (DeepL)",
  "Italian (DeepL)",
  "Dutch (DeepL)",
  "Polish (DeepL)",
  "Russian (DeepL)",
  "Portuguese (DeepL)",
  "Chinese (DeepL)",
  "Japanese (DeepL)",
  "Bulgarian (DeepL)",
  "Czech (DeepL)",
  "Danish (DeepL)",
  "Greek (DeepL)",
  "Estonian (DeepL)",
  "Finnish (DeepL)",
  "Hungarian (DeepL)",
  "Lithuanian (DeepL)",
  "Latvian (DeepL)",
  "Romanian (DeepL)",
  "Slovak (DeepL)",
  "Slovenian (DeepL)",
  "Swedish (DeepL)",
  "Indonesian (DeepL)",
  "Turkish (DeepL)",
  "Korean (DeepL)",
  "Norwegian (DeepL)",
  "Ukrainian (DeepL)",
  "Arabic (DeepL)"
  );
  $language_codes_deepl = array(
      "EN-",
      "DE-",
      "FR-",
      "ES-",
      "IT-",
      "NL-",
      "PL-",
      "RU-",
      "PT-",
      "ZH-",
      "JA-",
      "BG-",
      "CS-",
      "DA-",
      "EL-",
      "ET-",
      "FI-",
      "HU-",
      "LT-",
      "LV-",
      "RO-",
      "SK-",
      "SL-",
      "SV-",
      "ID-",
      "TR-",
      "KO-",
      "NB-",
      "UK-",
      "AR-"
  );
  $language_names_bing = array(
     "English (Microsoft Translator)",
     "Arabic (Microsoft Translator)",
     "Bosnian (Latin) (Microsoft Translator)",
     "Bulgarian (Microsoft Translator)",
     "Catalan (Microsoft Translator)",
     "Chinese Simplified (Microsoft Translator)",
     "Chinese Traditional (Microsoft Translator)",
     "Croatian (Microsoft Translator)",
     "Czech (Microsoft Translator)",
     "Danish (Microsoft Translator)",
     "Dutch (Microsoft Translator)",
     "Estonian (Microsoft Translator)",
     "Finnish (Microsoft Translator)",
     "French (Microsoft Translator)",
     "German (Microsoft Translator)",
     "Greek (Microsoft Translator)",
     "Haitian Creole (Microsoft Translator)",
     "Hebrew (Microsoft Translator)",
     "Hindi (Microsoft Translator)",
     "Hmong Daw (Microsoft Translator)",
     "Hungarian (Microsoft Translator)",
     "Indonesian (Microsoft Translator)",
     "Italian (Microsoft Translator)",
     "Japanese (Microsoft Translator)",
     "Kiswahili (Microsoft Translator)",
     "Klingon (Microsoft Translator)",
     "Klingon (pIqaD) (Microsoft Translator)",
     "Korean (Microsoft Translator)",
     "Latvian (Microsoft Translator)",
     "Lithuanian (Microsoft Translator)",
     "Malay (Microsoft Translator)",
     "Maltese (Microsoft Translator)",
     "Norwegian (Microsoft Translator)",
     "Persian (Microsoft Translator)",
     "Polish (Microsoft Translator)",
     "Portuguese (Microsoft Translator)",
     "Queretaro Otomi (Microsoft Translator)",
     "Romanian (Microsoft Translator)",
     "Russian (Microsoft Translator)",
     "Serbian (Cyrillic) (Microsoft Translator)",
     "Serbian (Latin) (Microsoft Translator)",
     "Slovak (Microsoft Translator)",
     "Slovenian (Microsoft Translator)",
     "Spanish (Microsoft Translator)",
     "Swedish (Microsoft Translator)",
     "Thai (Microsoft Translator)",
     "Turkish (Microsoft Translator)",
     "Ukrainian (Microsoft Translator)",
     "Urdu (Microsoft Translator)",
     "Vietnamese (Microsoft Translator)",
     "Welsh (Microsoft Translator)",
     "Yucatec Maya (Microsoft Translator)",
   
     "Afrikaans (Microsoft Translator)",
     "Albanian (Microsoft Translator)",
     "Amharic (Microsoft Translator)",
     "Armenian (Microsoft Translator)",
     "Assamese (Microsoft Translator)",
     "Azerbaijani (Microsoft Translator)",
     "Bangla (Microsoft Translator)", 
     "Bashkir (Microsoft Translator)",
     "Basque (Microsoft Translator)",
     "Cantonese (Microsoft Translator)",
     "Chinese (Literary) (Microsoft Translator)",
     "Dari (Microsoft Translator)",
     "Divehi (Microsoft Translator)",
     "Faroese (Microsoft Translator)",
     "Fijian (Microsoft Translator)",
     "Filipino (Microsoft Translator)",
     "French (Canada) (Microsoft Translator)",
     "Galician (Microsoft Translator)",
     "Georgian (Microsoft Translator)",
     "Gujarati (Microsoft Translator)",
     "Icelandic (Microsoft Translator)",
     "Inuinnaqtun (Microsoft Translator)",
     "Inuktitut (Microsoft Translator)",
     "Inuktitut (Latin) (Microsoft Translator)",
     "Irish (Microsoft Translator)",
     "Kannada (Microsoft Translator)",
     "Kazakh (Microsoft Translator)",
     "Khmer (Microsoft Translator)",
     "Kurdish (Central) (Microsoft Translator)",
     "Kurdish (Northern) (Microsoft Translator)",
     "Kyrgyz (Cyrillic) (Microsoft Translator)",
     "Lao (Microsoft Translator)",
     "Macedonian (Microsoft Translator)",
     "Malagasy (Microsoft Translator)",
     "Malayalam (Microsoft Translator)",
     "Maori (Microsoft Translator)",
     "Marathi (Microsoft Translator)",
     "Mongolian (Cyrillic) (Microsoft Translator)",
     "Mongolian (Traditional) (Microsoft Translator)",
     "Myanmar (Microsoft Translator)",
     "Nepali (Microsoft Translator)",
     "Odia (Microsoft Translator)",
     "Pashto (Microsoft Translator)",
     "Portuguese (Portugal) (Microsoft Translator)",
     "Punjabi (Microsoft Translator)",
     "Samoan (Microsoft Translator)",
     "Somali (Arabic) (Microsoft Translator)",
     "Swahili (Latin) (Microsoft Translator)",
     "Tahitian (Microsoft Translator)",
     "Tamil (Microsoft Translator)",
     "Tatar (Latin) (Microsoft Translator)",
     "Telugu (Microsoft Translator)",
     "Tibetan (Microsoft Translator)",
     "Tigrinya (Microsoft Translator)",
     "Tongan (Microsoft Translator)",
     "Turkmen (Latin) (Microsoft Translator)",
     "Upper Sorbian (Microsoft Translator)",
     "Uyghur (Arabic) (Microsoft Translator)",
     "Uzbek (Microsoft Translator)",
     "Zulu (Microsoft Translator)"
     );
 
     $language_codes_bing = array(
         "en!",
         "ar!",
         "bs-Latn!",
         "bg!",
         "ca!",
         "zh-CHS!",
         "zh-CHT!",
         "hr!",
         "cs!",
         "da!",
         "nl!",
         "et!",
         "fi!",
         "fr!",
         "de!",
         "el!",
         "ht!",
         "he!",
         "hi!",
         "mww!",
         "hu!",
         "id!",
         "it!",
         "ja!",
         "sw!",
         "tlh!",
         "tlh-Qaak!",
         "ko!",
         "lv!",
         "lt!",
         "ms!",
         "mt!",
         "nor!",
         "fa!",
         "pl!",
         "pt!",
         "otq!",
         "ro!",
         "ru!",
         "sr-Cyrl!",
         "sr-Latn!",
         "sk!",
         "sl!",
         "es!",
         "sv!",
         "th!",
         "tr!",
         "uk!",
         "ur!",
         "vi!",
         "cy!",
         "yua!",
         
         "af!",
         "sq!",
         "am!",
         "hy!",
         "as!",
         "az!",
         "bn!",
         "ba!",
         "eu!",
         "yue!",
         "lzh!",
         "prs!",
         "dv!",
         "fo!",
         "fj!",
         "fil!",
         "fr-ca!",
         "gl!",
         "ka!",
         "gu!",
         "is!",
         "ikt!",
         "iu!",
         "iu-Latn!",
         "ga!",
         "kn!",
         "kk!",
         "km!",
         "ku!",
         "kmr!",
         "ky!",
         "lo!",
         "mk!",
         "mg!",
         "ml!",
         "mi!",
         "mr!",
         "mn-Cyrl!",
         "mn-Mong!",
         "my!",
         "ne!",
         "or!",
         "ps!",
         "pt-pt!",
         "pa!",
         "sm!",
         "so!",
         "sw!",
         "ty!",
         "ta!",
         "tt!",
         "te!",
         "bo!",
         "ti!",
         "to!",
         "tk!",
         "hsb!",
         "ug!",
         "uz!",
         "zu!"
     );
?>